"""Portfolio, candle and dataset-coverage verification for parity reports.

The previous report summed per-trade percentages and called the sum "net return", never
compared reconstructed candles against the canonical dataset, and bound its verdict to
nothing - so a report stayed "PASS" after the manifest, strategy or data underneath it
changed.

This module supplies the three missing pieces:

- an actual equity curve under the manifest's compounding rule, with the arithmetic sum
  and the compounded portfolio return reported under names that cannot be confused,
- a field-by-field candle comparison with explicit missing / extra / duplicated /
  mismatched buckets,
- raw-dataset coverage validation and an input binding (hashes + tool version) that makes
  a stale report detectable.
"""
from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

# Bumped whenever the verification semantics change; a report generated by an older tool
# is not comparable with one generated by this code.
PARITY_TOOL_VERSION = "2.0"

# Fields compared per candle. Volume is compared with a relative tolerance because it is
# a sum of many Decimal quantities; prices are compared against the symbol's tick size.
OHLCV_FIELDS = ("open", "high", "low", "close", "volume")


# --- equity curve -------------------------------------------------------------


@dataclass
class TradeSizing:
    """Requested versus actually constrained size for one trade."""

    trade_id: int
    entry_time_utc: str
    requested_quantity: Decimal
    constrained_quantity: Decimal
    entry_price: Decimal
    exit_price: Decimal

    @property
    def size_difference(self) -> Decimal:
        return self.requested_quantity - self.constrained_quantity

    def to_dict(self) -> Dict[str, Any]:
        return {
            "trade_id": self.trade_id,
            "entry_time_utc": self.entry_time_utc,
            "requested_quantity": str(self.requested_quantity),
            "constrained_quantity": str(self.constrained_quantity),
            "size_difference": str(self.size_difference),
            "entry_price": str(self.entry_price),
            "exit_price": str(self.exit_price),
        }


@dataclass
class EquityCurve:
    """Portfolio result of replaying trades under the manifest's sizing rule."""

    initial_balance: Decimal
    final_balance: Decimal
    points: List[Tuple[int, Decimal]] = field(default_factory=list)
    sizing: List[TradeSizing] = field(default_factory=list)
    max_drawdown_pct: Decimal = Decimal("0")

    @property
    def compounded_return_pct(self) -> Decimal:
        """Portfolio return: what the account actually did, start to finish."""
        if self.initial_balance <= 0:
            return Decimal("0")
        return (self.final_balance - self.initial_balance) / self.initial_balance * Decimal("100")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "initial_balance": str(self.initial_balance),
            "final_balance": str(self.final_balance),
            "compounded_portfolio_return_pct": float(self.compounded_return_pct),
            "max_drawdown_pct": float(self.max_drawdown_pct),
            "trades": len(self.sizing),
            "sizing": [s.to_dict() for s in self.sizing],
        }


def arithmetic_sum_of_trade_pct(trade_pcts: Iterable[float]) -> Decimal:
    """Plain sum of per-trade percentages.

    This is NOT a portfolio return: it ignores compounding and position sizing. It is
    reported alongside the compounded return so the two can never be conflated again.
    """
    return sum((Decimal(str(p)) for p in trade_pcts), Decimal("0"))


def build_equity_curve(
    trades: Sequence[Any],
    initial_balance: Decimal,
    leverage: Decimal = Decimal("1"),
    taker_fee: Decimal = Decimal("0.0005"),
    compounding: bool = True,
    step_size: Optional[Decimal] = None,
    min_qty: Decimal = Decimal("0"),
) -> EquityCurve:
    """Replays trades as a real account: stake, size, fill, fee, settle, repeat.

    ``compounding`` follows the manifest's ``stake_rule``: full_compounding stakes the
    whole running balance, otherwise each trade stakes the initial balance.
    """
    balance = Decimal(str(initial_balance))
    peak = balance
    curve = EquityCurve(initial_balance=balance, final_balance=balance)
    curve.points.append((0, balance))

    for idx, trade in enumerate(trades, start=1):
        entry_px = Decimal(str(trade.entry_price))
        exit_px = Decimal(str(trade.exit_price))
        if entry_px <= 0:
            continue

        stake = balance if compounding else Decimal(str(initial_balance))
        notional = stake * Decimal(str(leverage))
        requested_qty = notional / entry_px
        constrained_qty = requested_qty
        if step_size and step_size > 0:
            constrained_qty = (requested_qty // step_size) * step_size
        if constrained_qty < min_qty:
            constrained_qty = Decimal("0")

        gross = (exit_px - entry_px) * constrained_qty
        fees = (entry_px + exit_px) * constrained_qty * Decimal(str(taker_fee))
        balance += gross - fees

        curve.sizing.append(TradeSizing(
            trade_id=getattr(trade, "trade_id", idx),
            entry_time_utc=str(getattr(trade, "entry_time_utc", "")),
            requested_quantity=requested_qty,
            constrained_quantity=constrained_qty,
            entry_price=entry_px,
            exit_price=exit_px,
        ))
        curve.points.append((idx, balance))
        peak = max(peak, balance)
        if peak > 0:
            drawdown = (peak - balance) / peak * Decimal("100")
            curve.max_drawdown_pct = max(curve.max_drawdown_pct, drawdown)

    curve.final_balance = balance
    return curve


def verify_sizing(curve: EquityCurve, tolerance: Optional[Decimal] = None) -> List[str]:
    """Reports trades whose constrained size differs materially from the requested size."""
    problems: List[str] = []
    for sizing in curve.sizing:
        if sizing.constrained_quantity <= 0:
            problems.append(
                f"Trade {sizing.trade_id}: requested {sizing.requested_quantity} rounds to zero "
                f"under the exchange step size; the benchmark assumed a filled position."
            )
            continue
        limit = tolerance if tolerance is not None else sizing.requested_quantity * Decimal("0.01")
        if abs(sizing.size_difference) > limit:
            problems.append(
                f"Trade {sizing.trade_id}: requested {sizing.requested_quantity} but exchange "
                f"constraints allow {sizing.constrained_quantity} "
                f"(difference {sizing.size_difference} exceeds {limit})."
            )
    return problems


# --- candle parity ------------------------------------------------------------


@dataclass
class CandleParityResult:
    """Field-by-field comparison of reconstructed candles against canonical data."""

    compared: int = 0
    matched: int = 0
    missing: List[int] = field(default_factory=list)
    extra: List[int] = field(default_factory=list)
    duplicated: List[int] = field(default_factory=list)
    mismatched: List[str] = field(default_factory=list)

    @property
    def parity_pct(self) -> float:
        return (self.matched / self.compared * 100.0) if self.compared else 0.0

    @property
    def passed(self) -> bool:
        return not (self.missing or self.extra or self.duplicated or self.mismatched) and self.compared > 0

    def classify(self) -> Dict[str, Any]:
        """Summarises *what kind* of disagreement this is, not just how much.

        Boundary-assignment differences show up as adjacent bars whose volume deltas
        cancel: the same quantity sits on the other side of a bucket edge. That is a
        source-semantics difference between the raw archive and the canonical dataset,
        and it reads very differently from corrupted or lost data, where nothing cancels.
        """
        fields: Dict[str, int] = {}
        deltas: Dict[int, Decimal] = {}
        for entry in self.mismatched:
            bucket_text, _, detail = entry.partition(": ")
            field_name = detail.split(" ", 1)[0]
            fields[field_name] = fields.get(field_name, 0) + 1
            if field_name != "volume":
                continue
            try:
                bucket = int(bucket_text)
                actual, canonical = detail.split(" != canonical ")
                deltas[bucket] = (Decimal(actual.split(" ")[-1])
                                  - Decimal(canonical.split(" ")[0]))
            except (ValueError, ArithmeticError):
                continue

        conserved = sum(
            1 for b, d in deltas.items()
            if any(abs(d + other) <= abs(d) / Decimal("1000")
                   for ob, other in deltas.items() if ob != b)
        )
        net = sum(deltas.values(), Decimal("0"))
        return {
            "fields": fields,
            "volume_mismatched_bars": len(deltas),
            "volume_deltas_cancelling_with_an_adjacent_bar": conserved,
            "net_volume_difference": str(net),
            "likely_cause": (
                "bucket-boundary assignment differs between the raw aggTrade archive and "
                "the canonical dataset (volume is conserved, only reassigned)"
                if deltas and conserved == len(deltas)
                else "unexplained: volume is not conserved across adjacent bars"
                if deltas else "no volume disagreement"
            ),
        }

    def to_dict(self) -> Dict[str, Any]:
        return {
            "compared": self.compared,
            "matched": self.matched,
            "candle_ohlcv_parity_pct": self.parity_pct,
            "missing_open_times": self.missing[:50],
            "extra_open_times": self.extra[:50],
            "duplicated_open_times": self.duplicated[:50],
            "mismatches": self.mismatched[:50],
            "missing_count": len(self.missing),
            "extra_count": len(self.extra),
            "duplicated_count": len(self.duplicated),
            "mismatch_count": len(self.mismatched),
            "diagnosis": self.classify(),
        }


def compare_candles(
    reconstructed: Sequence[Any],
    canonical: Sequence[Any],
    tick_size: Decimal,
    volume_tolerance_pct: Decimal = Decimal("0.0001"),
) -> CandleParityResult:
    """Compares every evaluation-window candle, timestamp and OHLCV field.

    Price tolerance is one tick: two reconstructions of the same trades cannot differ by
    less than the smallest representable price increment, and anything larger is a real
    disagreement. Volume uses a tiny relative tolerance because it is a Decimal sum whose
    ordering may differ.
    """
    result = CandleParityResult()

    recon_by_time: Dict[int, Any] = {}
    for candle in reconstructed:
        if candle.open_time in recon_by_time:
            result.duplicated.append(candle.open_time)
        recon_by_time[candle.open_time] = candle

    canon_by_time = {c.open_time: c for c in canonical}

    result.missing = sorted(set(canon_by_time) - set(recon_by_time))
    result.extra = sorted(set(recon_by_time) - set(canon_by_time))

    for open_time in sorted(set(canon_by_time) & set(recon_by_time)):
        result.compared += 1
        expected, actual = canon_by_time[open_time], recon_by_time[open_time]
        ok = True

        if expected.close_time != actual.close_time:
            result.mismatched.append(
                f"{open_time}: close_time {actual.close_time} != canonical {expected.close_time}"
            )
            ok = False

        for name in OHLCV_FIELDS:
            exp = Decimal(str(getattr(expected, name)))
            act = Decimal(str(getattr(actual, name)))
            if name == "volume":
                limit = abs(exp) * volume_tolerance_pct
            else:
                limit = tick_size
            if abs(exp - act) > limit:
                result.mismatched.append(
                    f"{open_time}: {name} {act} != canonical {exp} (tolerance {limit})"
                )
                ok = False

        if ok:
            result.matched += 1

    return result


# --- raw dataset coverage -----------------------------------------------------


def required_raw_months(window_start: str, window_end: str) -> List[str]:
    """Every YYYY-MM month a UTC evaluation window touches, inclusive."""
    start = datetime.fromisoformat(str(window_start).replace("Z", "+00:00")).astimezone(timezone.utc)
    end = datetime.fromisoformat(str(window_end).replace("Z", "+00:00")).astimezone(timezone.utc)
    months: List[str] = []
    cursor = start.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    while cursor <= end:
        months.append(cursor.strftime("%Y-%m"))
        cursor = (cursor + timedelta(days=32)).replace(day=1)
    return months


def resolve_raw_paths(manifest: Dict[str, Any], base_dir: Path) -> List[Path]:
    """Raw aggTrade files the manifest declares, in declaration order."""
    data_cfg = manifest.get("data", {}) or {}
    declared = data_cfg.get("dataset_aggtrade_paths")
    if not declared:
        single = data_cfg.get("dataset_aggtrade_path")
        declared = [single] if single else []
    return [(Path(base_dir) / p).resolve() for p in declared]


def validate_raw_coverage(manifest: Dict[str, Any], base_dir: Path) -> Tuple[bool, List[str], List[Path]]:
    """Checks the declared raw files cover the whole evaluation window and exist on disk.

    Returns (ok, errors, resolved_paths). Replay must not start when this fails: a window
    replayed over partial raw data silently produces a different trade set.
    """
    data_cfg = manifest.get("data", {}) or {}
    benchmark_id = manifest.get("benchmark_id", "UNKNOWN")
    start = data_cfg.get("evaluation_window_start")
    end = data_cfg.get("evaluation_window_end")
    errors: List[str] = []

    if not start or not end:
        return False, [f"RAW COVERAGE ERROR ({benchmark_id}): evaluation window is not defined"], []

    needed = required_raw_months(start, end)
    paths = resolve_raw_paths(manifest, base_dir)
    covered = {p.stem for p in paths}

    missing_months = [m for m in needed if m not in covered]
    if missing_months:
        errors.append(
            f"RAW COVERAGE ERROR ({benchmark_id}): evaluation window {start} .. {end} needs "
            f"{len(needed)} monthly raw file(s) {needed}, but the manifest declares "
            f"{sorted(covered) or 'none'}. Missing: {missing_months}."
        )

    absent = [str(p) for p in paths if not p.exists()]
    if absent:
        errors.append(
            f"RAW COVERAGE ERROR ({benchmark_id}): declared raw file(s) not found on disk: {absent}"
        )

    return (not errors), errors, paths


# --- input binding ------------------------------------------------------------


def file_hash(path: Path, chunk: int = 1 << 20) -> Optional[str]:
    """SHA-256 of a file, or None when it does not exist."""
    path = Path(path)
    if not str(path).strip() or not path.is_file():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        while block := fh.read(chunk):
            digest.update(block)
    return digest.hexdigest()


def bind_inputs(
    manifest_path: Path,
    manifest: Dict[str, Any],
    base_dir: Path,
    raw_paths: Optional[Sequence[Path]] = None,
) -> Dict[str, Any]:
    """Hashes every input a parity verdict depends on.

    A report carrying this binding can be checked later: if any hash has moved, the
    verdict no longer describes the files on disk.
    """
    base_dir = Path(base_dir)
    strategy = manifest.get("strategy", {}) or {}
    data_cfg = manifest.get("data", {}) or {}

    binding: Dict[str, Any] = {
        "tool_version": PARITY_TOOL_VERSION,
        "generated_at_ms": int(time.time() * 1000),
        "manifest_path": str(Path(manifest_path).name),
        "manifest_hash": file_hash(manifest_path),
        "strategy_hash": file_hash(base_dir / strategy["source_file"]) if strategy.get("source_file") else None,
        "helper_hash": file_hash(base_dir / strategy["helper_file"]) if strategy.get("helper_file") else None,
        "benchmark_csv_hash": file_hash(base_dir / manifest["benchmark_result_reference"]) if manifest.get("benchmark_result_reference") else None,
        "canonical_candles_hash": file_hash(base_dir / data_cfg["dataset_candle_path"]) if data_cfg.get("dataset_candle_path") else None,
        "raw_file_hashes": {},
    }
    for path in (raw_paths or resolve_raw_paths(manifest, base_dir)):
        binding["raw_file_hashes"][Path(path).name] = file_hash(path)
    return binding


def binding_differences(saved: Optional[Dict[str, Any]], current: Dict[str, Any]) -> List[str]:
    """Which bound inputs have changed since a report was written."""
    if not saved:
        return ["Report carries no input binding; it cannot be trusted"]

    differences: List[str] = []
    for key in ("tool_version", "manifest_hash", "strategy_hash", "helper_hash",
                "benchmark_csv_hash", "canonical_candles_hash"):
        if saved.get(key) != current.get(key):
            differences.append(f"{key} changed: {saved.get(key)} -> {current.get(key)}")

    saved_raw = saved.get("raw_file_hashes") or {}
    current_raw = current.get("raw_file_hashes") or {}
    for name in sorted(set(saved_raw) | set(current_raw)):
        if saved_raw.get(name) != current_raw.get(name):
            differences.append(f"raw file {name} changed: {saved_raw.get(name)} -> {current_raw.get(name)}")
    return differences


def report_is_stale(report: Dict[str, Any], current_binding: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """Whether a saved report's bound inputs still match what is on disk."""
    differences = binding_differences(report.get("input_binding"), current_binding)
    return bool(differences), differences
